### ISSUE TITLE
nomacs flatpak does not appear in "Open with list" of right click.

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.nomacs.ImageLounge#1]
Hi. I noticed that nomacs flatpak does not, currently, appearing within "Open with list" of right click.

Please notice it is not necessary to make it directly appearing within this list. There is option in "Open with list" called "Other application". It is quit suitable if user can use "Other application" sub-option of "Open with list" of right click, to brows & manipulate needed application.

**Comment by TingPing** [comment]
Do you mean in your file manager? What filetype and which file manager because the desktop file looks fine.

**Comment by Nokia808** [comment]
@TingPing 
Hi. Sorry for that: I installed nomacs flatpak BESIDE nomacs .rpm from my official Fedora repositories. 
When I read your replay, I became suspicious. So, I removed .rpm package then reset my system then remove icon of .rpm package & every think become normal !

When I was installing both .rpm & flatpak package, this issue was existing & my Cinnamon menu show 2 icons: nomacs & "nomacs flatpak", but "Open with list" of right click show only .rpm package icon ! But when I removed .rpm package, the flatpak icon appeared in "Open with list" as just "nomacs".

Please close this issue if it is not a confliction issue between .rpm & flatpak packages (I'm not sure?).
