### ISSUE TITLE
Please add extensions to flatpak package

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.nomacs.ImageLounge#2]
Hi. This is just a reminder for the future plan to add the nomacs' extensions to the flatpak package.

Best.

**Comment by Nokia808** [comment]
@diemmarkus 
Hi.
Dear it pass more than 24 hrs from closing this issue & commit to add plug-ins, but till now I can not receive update for nomacs containing new features ! Whatever I run "flatpak update" there is no thing to do ! Kindly, can you investigate what is going on ... !

**Comment by diemmarkus** [comment]
Hi,

1. I generally close issues if they are fixed in the master (that means, fixes/features become available in the upcoming release)
2. since it is in the beta channel, you can actually [test it](https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/)

best,
markus
