### ISSUE TITLE
Use /bin/sh instead of /bin/bash

### ISSUE THREAD

**Issue by a1346054** [flathub/org.nomacs.ImageLounge#3]
Please consider using /bin/sh instead of /bin/bash for https://github.com/flathub/org.nomacs.ImageLounge/blob/master/build.sh

and additionally run the .sh script through [shellcheck](https://www.shellcheck.net/) there are a few issues with the script.

**Comment by barthalion** [comment]
It's not a bug. Bash is available in both runtime and Sdk.

**Comment by a1346054** [comment]
Yes, you're right, it is not a bug. However, it is considered best practice for portability.
