### ISSUE TITLE
Flatpak package is not up to date !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.nomacs.ImageLounge#4]
Hi. I detect that flatpak package is not up to date ! Last version is 3.14.2 while current flatpak version is 3.14.
The current .rpm package in official Fedora repositories (a 3rd party packager not official developer package) for Fedora 32 is 3.14.2 !

**Comment by diemmarkus** [comment]
3.14.2 mainly patches issues for windows (svg loading) - that's why we didn't bring it to flathub.
